USE GymManagementDB;
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Quyen')
BEGIN
    CREATE TABLE Quyen (
        MaQuyen INT IDENTITY(1,1) PRIMARY KEY,
        TenBang NVARCHAR(100) NOT NULL,
        HanhDong NVARCHAR(50) NOT NULL,
        MoTa NVARCHAR(200),
        CONSTRAINT UQ_Quyen UNIQUE (TenBang, HanhDong)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TaiKhoan_Quyen')
BEGIN
    CREATE TABLE TaiKhoan_Quyen (
        MaTK INT NOT NULL FOREIGN KEY REFERENCES TaiKhoan(MaTK),
        MaQuyen INT NOT NULL FOREIGN KEY REFERENCES Quyen(MaQuyen),
        PRIMARY KEY (MaTK, MaQuyen)
    );
END
GO

DELETE FROM TaiKhoan_Quyen;
DELETE FROM Quyen;
DELETE FROM HoaDon;
DELETE FROM PhanCong;
DELETE FROM DangKyGoi;
DELETE FROM CaLam;
DELETE FROM GoiTap;
DELETE FROM HuanLuyenVien;
DELETE FROM HocVien;
DELETE FROM TaiKhoan;
GO

DBCC CHECKIDENT ('HocVien', RESEED, 0);
DBCC CHECKIDENT ('HuanLuyenVien', RESEED, 0);
DBCC CHECKIDENT ('CaLam', RESEED, 0);
DBCC CHECKIDENT ('GoiTap', RESEED, 0);
DBCC CHECKIDENT ('DangKyGoi', RESEED, 0);
DBCC CHECKIDENT ('PhanCong', RESEED, 0);
DBCC CHECKIDENT ('HoaDon', RESEED, 0);
DBCC CHECKIDENT ('TaiKhoan', RESEED, 0);
DBCC CHECKIDENT ('Quyen', RESEED, 0);
GO